#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Saladio.Resource", IsApplication=true)]

namespace Saladio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int SaladioPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SaladioPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int ButtonGradientRadius = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ButtonPadding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ButtonSolidRadius = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ButtonStrokeWidth = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int HorizontalMargin = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int ScreenBottomMargin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ScreenLeftMargin = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ScreenRightMargin = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ScreenTopMargin = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int VerticalMargin = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_pie_salad_64 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pic_pie_salad = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pic_salad_1 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int btnWizard = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int layoutContent = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int layoutWizardContainer = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentWelcome = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentWizard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Start = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public const int ApplicationName = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int BtnStart = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Welcome1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Welcome2 = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int SaladioActionBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int SaladioButton = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int SaladioTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
