#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Saladio.Resource", IsApplication=true)]

namespace Saladio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int GenderTypes = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050006
			public const int ButtonGradientColor = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ButtonSolidColor = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int CustomSaladInformationBackground = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int EditTextBackground = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int EditTextStroke = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int ListDividerStroke = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int PlusMinusButtonNormal = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int PlusMinusButtonPressed = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int PlusMinusButtonStroke = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int SaladComponentGroupStroke = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int SaladioPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SaladioPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int SaladioPrimaryDimmedLight = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int SaladioPrimaryLight = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int SaladioSecondary = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060007
			public const int ButtonGradientBottom = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int ButtonGradientLeft = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int ButtonGradientRadius = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ButtonPadding = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int ButtonSolidRadius = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int ButtonSolidRight = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ButtonSolidTop = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int ButtonStrokeWidth = 2131099650;
			
			// aapt resource value: 0x7f060020
			public const int CustomSaladInformationMinHeight = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int CustomSaladInformationRadius = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int CustomSaladInformationTextSize = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int DividerMargin = 2131099677;
			
			// aapt resource value: 0x7f060008
			public const int EditTextFocusedStroke = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int EditTextPaddingBottom = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int EditTextPaddingLeft = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int EditTextPaddingRight = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int EditTextPaddingTop = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int EditTextRadius = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int FormDescriptionTextSize = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int HorizontalMargin = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int ListDividerStroke = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int PlusMinusButtonPadding = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int PlusMinusButtonSize = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int PlusMinusButtonStroke = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int SaladComponentGroupTitleHorizontalPadding = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int SaladComponentGroupTitleRadius = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int SaladComponentGroupTitleStroke = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int SaladComponentGroupTitleVerticalPadding = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int ScreenBottomMargin = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ScreenLeftMargin = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ScreenRightMargin = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int ScreenTopMargin = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int VerticalMargin = 2131099666;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSaladInformationStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_pie_salad_64 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pic_pie_salad = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pic_salad_1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PlusMinusButtonStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SaladCatagoryGroupTitleStyle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090012
			public const int btnMinus = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int btnPlus = 2131296276;
			
			// aapt resource value: 0x7f090002
			public const int btnWizard = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int contentFragment = 2131296256;
			
			// aapt resource value: 0x7f090016
			public const int divider = 2131296278;
			
			// aapt resource value: 0x7f09000f
			public const int etAddress1 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int etAddress2 = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int etBirthDate = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int etEmail = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int etFirstName = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int etLastName = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int etPassword = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int etPhone = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int etWeight = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int layoutContainer = 2131296273;
			
			// aapt resource value: 0x7f090018
			public const int layoutSaladComponents = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int lstCustomSalad = 2131296281;
			
			// aapt resource value: 0x7f090003
			public const int slidingTabs = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int spGender = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int txtItemSubTitle = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int txtItemTitle = 2131296262;
			
			// aapt resource value: 0x7f090013
			public const int txtQuantity = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int txtSaladComponent = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int txtSaladComponentGroup = 2131296279;
			
			// aapt resource value: 0x7f090004
			public const int viewPager = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int wizardContainer = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityStart = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentSlidingTabs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PagerItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PageSignUp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PageSignUpDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PageWelcome = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RowSaladComponent = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RowSaladComponentGroup = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TabAbout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TabOrderCustomSalad = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int BtnNext = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int BtnStart = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int Bullet = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int CustomSaladInformationGrams = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int CustomSaladInformationKilloCalorie = 2131165211;
			
			// aapt resource value: 0x7f070015
			public const int CustomSaladInformationOther = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int CustomSaladInformationPrice = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int CustomSaladInformationToman = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int CustomSaladInformationWeight = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int CustomSaladInformatonCalorie = 2131165208;
			
			// aapt resource value: 0x7f07001c
			public const int CustomSaladMoreDetails = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int CustomSaladSave = 2131165213;
			
			// aapt resource value: 0x7f070013
			public const int Female = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int FormDescriptionEmail = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int FormInputAddress1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int FormInputAddress2 = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int FormInputBirthDateHint = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int FormInputEmailHint = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int FormInputFirstNameHint = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int FormInputGenderHint = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int FormInputLastNameHint = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int FormInputPasswordHint = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int FormInputPhoneHint = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int FormInputWeightHint = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int Male = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int TabAbout = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int TabCustomSalad = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Welcome1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Welcome2 = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080004
			public const int CustomSaladInformation = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int CustomSaladInformationBar = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int PlusMinusButton = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int SaladComponentGroupTitle = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int SaladioActionBar = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int SaladioButton = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int SaladioEditText = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int SaladioListDivider = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int SaladioTextView = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int SaladioTheme = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int VerticalListDivider = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
